project:
  title: "true·vector"
  type: website
  output-dir: docs
  preview:
    port: 9999

website:
  favicon: "gradient.jpg"
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "ai"
        contents:
         - affective.qmd
         - general.qmd
         - knowledge.qmd
         - language.qmd
         - learning.qmd
         - perception.qmd
         - reasoning.qmd

format:
   html:
      css: styles.css
      html-math-method: mathml
      theme: superhero
      toc: true
      toc-expand: 1
      toc-location: left
      link-external-newwindow: true